<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />

    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="forearm_radius" value="0.02" />

    <xacro:property name="hand_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}"
                        xyz="0 0 ${arm_base_height/2}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0" />
        </collision>
    </link>

    <link name="forearm">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <xacro:wheel_inertia m="0.3" h="${forearm_length}" r="${forearm_radius}"
                        xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
        </collision>
    </link>

    <link name="hand">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <xacro:wheel_inertia m="0.3" h="${forearm_length}" r="${forearm_radius}"
                        xyz="0 0 ${forearm_length/2}" rpy="0 0 0" />
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0" />
        </collision>
    </link>

    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>
    <joint name="hand_forearm_joint" type="revolute">
        <parent link="forearm" />
        <child link="hand" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

</robot>