<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="wheel_radius" value="0.1" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <material name="redgreen" />
            </visual>

            <xacro:wheel_inertia m="1.0" h="${wheel_length}" r="${wheel_radius}"
                        xyz="0 0 0" rpy="${pi/2} 0 0" />

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="bluegreen" />
        </visual>

        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                        xyz="0 0 ${base_height/2}" rpy="0 0 0" />

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
    </link>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="castor_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <origin xyz="0 0 -0.05" rpy="0 0 0" />
            <material name="redblue" />
        </visual>

        <xacro:castor_inertia m="0.5" r="${wheel_radius/2}" xyz="0 0 -0.05" rpy="0 0 0" />
        
        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <origin xyz="0 0 -0.05" rpy="0 0 0" />
        </collision>
    </link>
    <link name="base_footprint" />

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length/4} ${(base_width + wheel_length)/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length/4} ${-(base_width + wheel_length)/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <joint name="base_castor_joint" type="fixed">
        <parent link="base_link" />
        <child link="castor_wheel_link" />
        <origin xyz="${base_length/3.0} 0 0" rpy="0 0 0" />
    </joint>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>

</robot>